[2023-08-06 17:47:09 -0700] [11107] [INFO] Starting gunicorn 21.2.0
[2023-08-06 17:47:09 -0700] [11107] [INFO] Listening at: http://127.0.0.1:5002 (11107)
[2023-08-06 17:47:09 -0700] [11107] [INFO] Using worker: sync
[2023-08-06 17:47:09 -0700] [11113] [INFO] Booting worker with pid: 11113
[2023-08-06 17:47:09 -0700] [11113] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/bk/repos/chesscom-analysis-unlocker/server.py", line 2, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
[2023-08-06 17:47:09 -0700] [11113] [INFO] Worker exiting (pid: 11113)
[2023-08-06 17:47:09 -0700] [11107] [ERROR] Worker (pid:11113) exited with code 3
[2023-08-06 17:47:09 -0700] [11107] [ERROR] Shutting down: Master
[2023-08-06 17:47:09 -0700] [11107] [ERROR] Reason: Worker failed to boot.
[2023-08-06 17:47:22 -0700] [11141] [INFO] Starting gunicorn 21.2.0
[2023-08-06 17:47:22 -0700] [11141] [INFO] Listening at: http://127.0.0.1:5002 (11141)
[2023-08-06 17:47:22 -0700] [11141] [INFO] Using worker: sync
[2023-08-06 17:47:22 -0700] [11147] [INFO] Booting worker with pid: 11147
[2023-08-06 17:47:22 -0700] [11147] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/bk/repos/chesscom-analysis-unlocker/server.py", line 2, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
[2023-08-06 17:47:22 -0700] [11147] [INFO] Worker exiting (pid: 11147)
[2023-08-06 17:47:22 -0700] [11141] [ERROR] Worker (pid:11147) exited with code 3
[2023-08-06 17:47:22 -0700] [11141] [ERROR] Shutting down: Master
[2023-08-06 17:47:22 -0700] [11141] [ERROR] Reason: Worker failed to boot.
[2023-08-06 17:48:23 -0700] [11268] [INFO] Starting gunicorn 21.2.0
[2023-08-06 17:48:23 -0700] [11268] [INFO] Listening at: http://127.0.0.1:5002 (11268)
[2023-08-06 17:48:23 -0700] [11268] [INFO] Using worker: sync
[2023-08-06 17:48:23 -0700] [11275] [INFO] Booting worker with pid: 11275
[2023-08-06 17:48:23 -0700] [11275] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/bk/repos/chesscom-analysis-unlocker/server.py", line 2, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
[2023-08-06 17:48:23 -0700] [11275] [INFO] Worker exiting (pid: 11275)
[2023-08-06 17:48:23 -0700] [11268] [ERROR] Worker (pid:11275) exited with code 3
[2023-08-06 17:48:23 -0700] [11268] [ERROR] Shutting down: Master
[2023-08-06 17:48:23 -0700] [11268] [ERROR] Reason: Worker failed to boot.
[2023-08-06 17:50:32 -0700] [11469] [INFO] Starting gunicorn 21.2.0
[2023-08-06 17:50:32 -0700] [11469] [INFO] Listening at: http://127.0.0.1:5002 (11469)
[2023-08-06 17:50:32 -0700] [11469] [INFO] Using worker: sync
[2023-08-06 17:50:32 -0700] [11476] [INFO] Booting worker with pid: 11476
[2023-08-06 17:50:32 -0700] [11476] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bk/repos/chesscom-analysis-unlocker/venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/bk/repos/chesscom-analysis-unlocker/server.py", line 4, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2023-08-06 17:50:32 -0700] [11476] [INFO] Worker exiting (pid: 11476)
[2023-08-06 17:50:32 -0700] [11469] [ERROR] Worker (pid:11476) exited with code 3
[2023-08-06 17:50:32 -0700] [11469] [ERROR] Shutting down: Master
[2023-08-06 17:50:32 -0700] [11469] [ERROR] Reason: Worker failed to boot.
[2023-08-06 17:51:38 -0700] [11646] [INFO] Starting gunicorn 21.2.0
[2023-08-06 17:51:38 -0700] [11646] [INFO] Listening at: http://127.0.0.1:5002 (11646)
[2023-08-06 17:51:38 -0700] [11646] [INFO] Using worker: sync
[2023-08-06 17:51:38 -0700] [11652] [INFO] Booting worker with pid: 11652
[2023-08-06 17:54:23 -0700] [11646] [INFO] Handling signal: term
[2023-08-06 17:54:23 -0700] [11652] [INFO] Worker exiting (pid: 11652)
[2023-08-06 17:54:23 -0700] [11646] [INFO] Shutting down: Master
[2023-08-06 17:55:11 -0700] [12177] [INFO] Starting gunicorn 21.2.0
[2023-08-06 17:55:11 -0700] [12177] [INFO] Listening at: http://127.0.0.1:5002 (12177)
[2023-08-06 17:55:11 -0700] [12177] [INFO] Using worker: sync
[2023-08-06 17:55:11 -0700] [12183] [INFO] Booting worker with pid: 12183
